### ISSUE TITLE
Transform this Todo list into issues

### ISSUE THREAD

**Issue by alexander-c-b** [alexander-c-b/AsciiMath#6]
-   [x] Handle unicode characters in "..."

-   [x] potential `addSpace` function:
    ```
    addSpace :: [Expr] -> [Expr]
    addSpace [] = []
    addSpace (x:xs) = addSpace_ xs
        where addSpace_ (x:xs)
                | needsSpace x = Space : x : addSpace_ xs
              addSpace_ other = other
    ```

-   [x] Space before differentials: `dx`, `dy`, `dA`... handle superscripts like `dx^2`.

-   [x] `boxed(...)`

-   [x] ~~Double harpoon arrow symbol~~

-   [x] Escape special characters like `#`

-   [x] Matrix syntax for column alignments

    ```
    {:#lr# 1 &!= 2 \\ 3 &= x + 3 :}
    ```

-   [x] Simplify AST

-   [x] Percent sign: `%`

-   [x] Units:

    Grammar: real number, optional e & ±integer, followed by any other expressions.
    
    Or: any expressions, followed by a simple expression.

    Identifiers in the expressions after the number are all converted to text; a space is also added between the number and the rest of the expressions.

    ```
    unit(6.626e-34 J*s)
    ```

    becomes

    ```
    6.626xx10^(-34) " " "J"*"s"
    ```

-   [x] ~~Chemicals~~:

    Grammar: optional initial integer; identifiers/numbers (numbers become subscripted); optional ^, optional number, then charge; optional phase.

    ```
    chem(2H30^+ (l))
    chem(SO4^2- (aq))
    ```

    becomes

    ```
    2"H"_3"O"_(("l"))^(+)
    "SO"_(4 ("aq"))^(2-)
    ```

-   [x] Matrices

    Search for `&` or `\\ `; if either is found, simply wrap them by `\begin{matrix}` and `\end{matrix}`.

**Comment by alexander-c-b** [comment]
The issues have been created.
